// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarshipServer.Data;

#nullable disable

namespace StarshipServer.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StarshipServer.Data.Models.Hull", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("Mass")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Armor");

                    b.HasIndex("Mass");

                    b.HasIndex("Name");

                    b.ToTable("Hulls");
                });

            modelBuilder.Entity("StarshipServer.Data.Models.Reactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnergyGainPerSec")
                        .HasColumnType("int");

                    b.Property<int>("EnergyMax")
                        .HasColumnType("int");

                    b.Property<int>("Mass")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EnergyGainPerSec");

                    b.HasIndex("EnergyMax");

                    b.HasIndex("Mass");

                    b.HasIndex("Name");

                    b.ToTable("Reactors");
                });

            modelBuilder.Entity("StarshipServer.Data.Models.Starship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HullId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ReactorId")
                        .HasColumnType("int");

                    b.Property<int>("ThrusterId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HullId");

                    b.HasIndex("Name");

                    b.HasIndex("Owner");

                    b.HasIndex("ReactorId");

                    b.HasIndex("ThrusterId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Starships");
                });

            modelBuilder.Entity("StarshipServer.Data.Models.Thruster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnergyDrainPerSec")
                        .HasColumnType("int");

                    b.Property<int>("Mass")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ThrustPerSec")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnergyDrainPerSec");

                    b.HasIndex("Mass");

                    b.HasIndex("Name");

                    b.HasIndex("ThrustPerSec");

                    b.ToTable("Thrusters");
                });

            modelBuilder.Entity("StarshipServer.Data.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DamagePerShot")
                        .HasColumnType("int");

                    b.Property<int>("EnergyDrainPerSec")
                        .HasColumnType("int");

                    b.Property<int>("Mass")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ShotsPerSec")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DamagePerShot");

                    b.HasIndex("EnergyDrainPerSec");

                    b.HasIndex("Mass");

                    b.HasIndex("Name");

                    b.HasIndex("ShotsPerSec");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("StarshipServer.Data.Models.Starship", b =>
                {
                    b.HasOne("StarshipServer.Data.Models.Hull", "Hull")
                        .WithMany()
                        .HasForeignKey("HullId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarshipServer.Data.Models.Reactor", "Reactor")
                        .WithMany()
                        .HasForeignKey("ReactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarshipServer.Data.Models.Thruster", "Thruster")
                        .WithMany()
                        .HasForeignKey("ThrusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarshipServer.Data.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hull");

                    b.Navigation("Reactor");

                    b.Navigation("Thruster");

                    b.Navigation("Weapon");
                });
#pragma warning restore 612, 618
        }
    }
}
